language: scala

scala:
  - 2.10.5

services:
  - redis-server
  - mongodb

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  # ensure the build errors if dependencies aren't available
  - ./bin/sbt ++$TRAVIS_SCALA_VERSION update

script:
  - ./bin/sbt ++$TRAVIS_SCALA_VERSION clean test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false
